### PR TITLE
Workaround to fix Asus VivoBooks not waking from suspend

### PR DESCRIPTION
**Pull request by realKarthikNair**

### CODE REVIEW

**Comment by ldrahnik** [comment]
@realKarthikNair Thank you. Could you please attach a link to the Ubuntu issue or Kernel issue?

**Comment by realKarthikNair** [comment]
I am no longer able to find the Vivobook specific issue. It got fixed itself on my VivoBook few months back (I'll edit the file and remove VivoBook)

But found these 2 threads with the exact issue and both of them are Asus Laptops. 

https://bbs.archlinux.org/viewtopic.php?id=268420
https://askubuntu.com/questions/1362001/ubuntu-21-04-wont-wake-from-sleep

**Comment by ldrahnik** [comment]
@realKarthikNair I face this issue atm but the reasons, why this happens, might be very wide. Because for me suspend feature worked when was system clearly installed. Elementary OS 6.1 Jólnir based on Ubuntu 20.04. Atm I use an updated kernel
 
```
$ uname -r
6.0.8-060008-generic
```

I have not had much time to debug this issue but in my case `systemd suspend` fails during waking up.

**Comment by realKarthikNair** [comment]
I get it. Shall I close the PR then?

**Comment by ldrahnik** [comment]
@realKarthikNair So my case was probably because is something wrong in suspend service from NumberPad driver in this org. IMHO I still do not know what was wrong, but, I removed that service from driver. Because I today reinstalled Elementary OS Jólnir 6.1 (based Ubuntu 20.04) and figured out disabling suspend service was key for get suspend working fine (after clear installation was suspend working, then not). But as I said, I could try during my last distro installation new packages so maybe exist more reasons why it did not work. I think this PR should be closed, ppl with this problem should open issues somewhere and try figure out what is wrong with installed packages for example and not be satisfied with workaround. Still, in case kernel/ubuntu issue exist, not patch yet, I agree with merge this PR but with mentioned kernel versions / links.

// I send to you e-mail from my e-mail mentioned this org title, check spam folder

**Comment by realKarthikNair** [comment]
Okay. I've replied you over email.

**Pull request closed without merging**
